# Generated by Django 4.0.4 on 2022-05-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hostelInformationModel',
            fields=[
                ('hostelName', models.CharField(max_length=100)),
                ('hostel_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('warden_name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField(max_length=10)),
                ('contact_email', models.EmailField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(max_length=100)),
                ('room_capacity', models.IntegerField(max_length=10)),
                ('room_price', models.IntegerField(max_length=10)),
                ('room_status', models.CharField(max_length=100)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelinformationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='hostelMapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_link1', models.CharField(max_length=1000, unique=True)),
                ('map_link2', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('map_link3', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('map_link4', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('map_link5', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelinformationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='hostelImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link1', models.CharField(max_length=1000, unique=True)),
                ('image_link2', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('image_link3', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('image_link4', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('image_link5', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('image_link6', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('image_link7', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('image_link8', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('image_link9', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('image_link10', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelinformationmodel')),
            ],
        ),
    ]
