# Generated by Django 4.0.2 on 2022-05-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_hostelallocatedtoyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelimagesmodel',
            name='hostel_id',
        ),
        migrations.AddField(
            model_name='hostelinformationmodel',
            name='hostel_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelimagesmodel'),
        ),
        migrations.AddField(
            model_name='hostelinformationmodel',
            name='hostel_type',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hostelimagesmodel',
            name='image_link1',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
