# Generated by Django 4.0.2 on 2022-05-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_rename_image_link1_hostelimagesmodel_image_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelimagesmodel',
            old_name='hostel_id',
            new_name='hostel_name',
        ),
    ]
