# Generated by Django 4.0.4 on 2022-05-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_alter_hostelinformationmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelallocatedtoyear',
            name='hostel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearAllocation', to='hostel.hostelinformationmodel'),
        ),
    ]
