# Generated by Django 4.0.4 on 2022-05-22 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_alter_hostelallocatedtoyear_hostel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelpreferencefirstyear',
            name='preferenceThree',
        ),
        migrations.RemoveField(
            model_name='hostelpreferencesecondyear',
            name='preferenceThree',
        ),
        migrations.AlterField(
            model_name='hostelallocatedtoyear',
            name='hostel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelinformationmodel'),
        ),
    ]
