# Generated by Django 4.0.4 on 2022-05-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
