# Generated by Django 4.0.4 on 2022-05-18 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        ('user', '0002_alter_user_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='hostel',
            field=models.ForeignKey(default='Unassigned', null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelinformationmodel'),
        ),
    ]
