# Generated by Django 4.0.4 on 2022-05-18 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        ('user', '0003_alter_student_fee_paid_alter_user_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='hostel',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelinformationmodel'),
        ),
    ]
