# Generated by Django 4.0.4 on 2022-05-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_student_sex_alter_user_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
