# Generated by Django 4.0.2 on 2022-05-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_student_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grad_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
