# Generated by Django 4.0.2 on 2022-05-22 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_hostelpreferencefirstyear_hostelpreferencesecondyear_and_more'),
        ('user', '0011_alter_student_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelinformationmodel'),
        ),
    ]
