# Generated by Django 4.0.4 on 2022-05-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_alter_hostelinformationmodel_description'),
        ('user', '0012_alter_user_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hostel',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelinformationmodel'),
        ),
    ]
