# Generated by Django 4.0.4 on 2022-05-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_alter_hostelallocatedtoyear_hostel_id'),
        ('user', '0013_alter_user_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hostel',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.hostelinformationmodel'),
        ),
    ]
